export enum TOOLS  {
    ADD_SLIDE = 'ADD_SLIDE',
    DELETE_SLIDE = 'DELETE_SLIDE',
    UNDO = 'UNDO',
    REDO = 'REDO',
    CIRCLE = 'CIRCLE',
    TRIANGLE = 'TRIANGLE',
    RECTANGLE = 'RECTANGLE',
    ADD_TEXT = 'ADD_TEXT',
    SAVE = 'SAVE',
    UPLOAD = 'UPLOAD',
    DO_PDF = 'DO_PDF',
    PREVIEW = 'PREVIEW'
}